### ISSUE TITLE
No module named '_tkinter'

### ISSUE THREAD

**Issue by erwincoumans** [Denys88/rl_games#169]
The latest rl_games imports turtle, which imports tkinter, leading to this error. Is this an absolutely unavoidable import?

FYI: I commented-out that 1st line from rl_games/algos_torch/sac_agent.py (from turtle import shape), and things seem to work fine without that import.

```
Traceback (most recent call last):
  File "runner.py", line 44, in <module>
    from rl_games.torch_runner import Runner
  File "F:\dev\rl_games\rl_games\torch_runner.py", line 19, in <module>
    from rl_games.algos_torch import sac_agent
  File "F:\dev\rl_games\rl_games\algos_torch\sac_agent.py", line 1, in <module>
    from turtle import shape
  File "c:\python37\lib\turtle.py", line 107, in <module>
    import tkinter as TK
  File "c:\python37\lib\tkinter\__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by Denys88** [comment]
@erwincoumans  looks like that line appeared accidentally. Probably ide decided I need it. 
Thanks
