### ISSUE TITLE
ImportError: libGL.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by gradeyw** [Denys88/rl_games#77]
Running 
`python rlg_train.py --task Ant`
from carbgym/python/rlgpu

gives the following error:

`Traceback (most recent call last):
  File "rlg_train.py", line 13, in <module>
    from rl_games.common import env_configurations, experiment, vecenv
  File "/home/dcg-adlr-gradeyw-source/rl_games/rl_games/common/env_configurations.py", line 1, in <module>
    from rl_games.common import wrappers
  File "/home/dcg-adlr-gradeyw-source/rl_games/rl_games/common/wrappers.py", line 8, in <module>
    import cv2
  File "/opt/conda/lib/python3.6/site-packages/cv2/__init__.py", line 5, in <module>
    from .cv2 import *
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
`

Using the master branch of carbgym and Python 3.6

**Comment by Denys88** [comment]
Fixed. I moved opencv import to the atari wrappers.
